HRApplication/Controllers/DepartmentController.cs
using HRApplication.Data;
using HRApplication.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRApplication.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService departmentService;

        public DepartmentController(IDepartmentService _departmentService)
        {
            departmentService = _departmentService;
        }
        public IActionResult Index()
        {
            Department department = new Department();
            return View("AddDepartment",department);
        }
        [HttpPost]
        public IActionResult CreateDepartment(Department department)
        {
            departmentService.CreateDepartment(department);
            department = new Department();
            return View("AddDepartment",department);
        }

        public IActionResult Department()
        {
            List<Department> departments = new List<Department>();
            return View("DepartmentList",departments);
        }

        public IActionResult GetDepartment()
        {
            string name = Request.Form["Name"];
            List<Department> departments= departmentService.GetDepartmentsByName(name);
            return View("DepartmentList",departments);
        }

        public IActionResult EditDepartment(int id)
        {

            Department department= departmentService.GetDepartmentById(id);

            return View("AddDepartment",department);
        }

        public IActionResult UpdateDepartment(Department department)
        {
            departmentService.UpdateDepartment(department);
            department = new Department();
            return View("AddDepartment",department);
        } 

        public IActionResult DeleteDepartment(int id)
        {
            departmentService.DeleteDepartment(id);
            List<Department> departments = new List<Department>();
            return View("DepartmentList",departments);
        }
    }
}

HRApplication/Controllers/EmployeeController.cs
using HRApplication.Data;
using HRApplication.Models;
using HRApplication.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace HRApplication.Controllers
{
    [Authorize(Roles ="Admin")]
    public class EmployeeController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly IEmployeeService employeeService;
        private readonly ICountryService countryService;
        private readonly IDepartmentService departmentService;
        private readonly ICityService cityService;

        public EmployeeController(IConfiguration _configuration,IEmployeeService _employeeService,ICountryService _countryService,IDepartmentService _departmentService,ICityService _cityService)
        {
            configuration = _configuration;
            employeeService = _employeeService;
            countryService = _countryService;
            departmentService = _departmentService;
            cityService = _cityService;
        }
        public IActionResult Index()
        {
            VmCompany vm = new VmCompany();
            vm.cities = cityService.GetCities();
            vm.countries = countryService.GetAllCountry();
            vm.departments = departmentService.GetDepartments();
            vm.employee = new Employee();
            return View("Add_Employee",vm);
        }

        public IActionResult CreateEmployee(VmCompany vm)
        {
            vm.cities = cityService.GetCities();
            vm.departments = departmentService.GetDepartments();
            vm.countries = countryService.GetAllCountry();

            string path = Path.Combine(Directory.GetCurrentDirectory(), configuration["FilePath"], vm.employee.Image.FileName);
            vm.employee.Image.CopyTo(new FileStream(path, FileMode.Create));
            vm.employee.Path= Path.Combine("http://localhost/HRApplication/img/",vm.employee.Image.FileName);

            employeeService.AddEmployee(vm.employee);

            vm.employee = new Employee();

            return View("Add_Employee",vm);
        }

        public IActionResult Employees()
        {
            IEnumerable<Employee> employees = employeeService.GetEmployees();

            return View("EmployeeList",employees);
        }

        public IActionResult GetEmployee()
        {
            string name = Request.Form["Name"];

            List<Employee> employees = employeeService.GetEmployeeByName(name);

            return View("EmployeeList",employees);
        }

        public IActionResult DeleteEmployee(int id)
        {

            IEnumerable<Employee> employees = employeeService.GetEmployees();
            employeeService.DeleteEmployee(id);

            return View("EmployeeList",employees);
        }

        public IActionResult EditEmployee(int id)
        {

            Employee emp = employeeService.GetEmployeeById(id);
            VmCompany vm = new VmCompany();
            vm.cities = cityService.GetCities();
            vm.countries = countryService.GetAllCountry();
            vm.departments = departmentService.GetDepartments();
            vm.employee = emp;
            return View("Add_Employee",vm);
        }

        public IActionResult UpdateEmployee(VmCompany vm)
        {

            employeeService.UpdateEmployee(vm.employee);
            vm.cities = cityService.GetCities();
            vm.countries = countryService.GetAllCountry();
            vm.departments = departmentService.GetDepartments();
            vm.employee = new Employee();
            return View("Add_Employee", vm);
        }

        public IActionResult GetEmployeesByDepartment(int id)
        {
            List<Employee> employees = employeeService.GetEmployeesByDepartment(id).ToList();
            return View("EmployeeList",employees);
        }



    }
}

HRApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HRApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HRApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HRApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HRApplication/Views/Shared/_LayoutPage.cshtml
@using Microsoft.AspNetCore.Identity
@using HRApplication.Data
@inject SignInManager<ApplicationUser> signIn
@{
    ViewData["Title"] = "_LayoutPage";
}


@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_LayoutPage</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid bg">
        <div class="row">
            <nav class="navbar-inverse">
                <div class="navbar-brand">
                    HR SYSTEM
                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-target="#menu1" data-toggle="collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="menu1" class="navbar-collapse collapse">

                    @if(signIn.IsSignedIn(User))
                        {

                        <ul class="nav navbar-nav">
                            <li>
                                <a asp-action="Index" asp-controller="Employee">New Employee</a>
                            </li>
                            <li>
                                <a asp-action="Employees" asp-controller="Employee">Employee List</a>
                            </li>
                            <li>
                                <a asp-action="Index" asp-controller="Department">Department</a>
                            </li>
                            <li>
                                <a asp-action="Department" asp-controller="Department">Department List</a>
                            </li>
                        </ul>
                    }
                    
                    <ul class="nav navbar-nav navbar-right">

                        @if (signIn.IsSignedIn(User))
                        {

                            <li><a class="glyphicon glyphicon-log-out" asp-controller="Account" asp-action="signOut"> Logout</a></li>
                        }
                        else
                        {

                            <li><a class="glyphicon glyphicon-log-in" asp-controller="Account" asp-action="SignIn"> SignIn</a></li>
                        }

                    </ul>
                </div>

            </nav>
        </div>

        <div class="row">
            <div class="col-xs-12">
                @RenderSection("Body",false)
            </div>

        </div>
    </div>
</body>
</html>